
      version: 2.1

      orbs:
        prisma: prisma_cloud/devops_security@2.0.0

      workflows:
        scan:
          jobs:
            - docker_build_and_save
            - prisma/image_scan:
                requires:
                  - docker_build_and_save
                prisma_cloud_compute_url: https://europe-west3.cloud.twistlock.com/eu-1610258
                prisma_cloud_compute_user: bbd7ac3c-9002-47ac-bbd8-cc5ddebffb3c
                prisma_cloud_compute_pass: Vz6EbtHwAhDLBZ2g9ycuHPlgq2I=
                image: 'myrepo/myimage:tag'
                image_tar: image.tar

