version: 2.1
jobs:
  build:
    docker:
    # Primary container image where all steps run.
     - image: cimg/base:current
    # Secondary container image on common network.
     - image: cimg/mariadb:10.6


    steps:
      # Run the built-in checkout script to checkout the code in this repo
      - checkout
      # Download twistcli from the configured Twistlock console
      - run: curl -k -u bbd7ac3c-9002-47ac-bbd8-cc5ddebffb3c:Vz6EbtHwAhDLBZ2g9ycuHPlgq2I= --output twistcli https://europe-west3.cloud.twistlock.com/eu-1610258/api/v1/util/twistcli
      # ...and ensure it's executable.
      - run: sudo chmod a+x twistcli
      
      # Build our project that is contained in the code
      # checked out above.

      - run: pwd && ls -l 
      - run: docker build -t cimg/mariadb:10.6:$CIRCLE_BRANCH .
      
      
      - run: ./twistcli images scan --details --address https://europe-west3.cloud.twistlock.com/eu-1610258 --user bbd7ac3c-9002-47ac-bbd8-cc5ddebffb3c --password Vz6EbtHwAhDLBZ2g9ycuHPlgq2I= sgordon/latest:$CIRCLE_BRANCH
      # Add --vulnerability-threshold and/or --compliance-threshold to this command to
      # fail builds based on the thresholds.
      # See twistcli documentation for more details.
  # add any additional commands needed to test the image, push to a registry, etc.

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
         context: SaaS
