version: 2.1

orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5

jobs:
  bina:
    docker:
      - image: alpine
    working_directory: /mnt/ramdisk
    steps:
      - run: |
          echo ‘#!/bin/sh’ > run.sh
          echo ‘echo Hello world!’ >> run.sh
          chmod +x run.sh
      - run: ./run.sh
  checkov_scan:
    docker:
      - image: bridgecrew/checkov:latest
    steps:
      # command will execute in an Ubuntu-based container
      # and can access MariaDB on localhost !
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          LOG_LEVEL=DEBUG checkov -d . --use-enforcement-rules -o cli --bc-api-key “$BC_API_KEY” --prisma-api-url “$PRISMA_API_URL” --repo-id schnitz-air/maagal --soft-fail
          #docker run --tty --volume $(pwd):/tf --workdir /tf bridgecrew/checkov --directory /tf
  TwistCLI:
    machine: # executor type
      image: ubuntu-2004:2022.07.1
    steps:
      - run: |
          curl --progress-bar -L --header “authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYXNjaG5pdHplckBwYWxvYWx0b25ldHdvcmtzLmNvbSIsInJvbGUiOiJhZG1pbiIsInJvbGVQZXJtcyI6W1syNTUsMjU1LDI1NSwyNTUsMjU1LDEyNywxXSxbMjU1LDI1NSwyNTUsMjU1LDI1NSwxMjcsMV1dLCJzZXNzaW9uVGltZW91dFNlYyI6NTk2LCJzYWFzVG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlKOS5leUp6ZFdJaU9pSmhjMk5vYm1sMGVtVnlRSEJoYkc5aGJIUnZibVYwZDI5eWEzTXVZMjl0SWl3aWMyVnlkbWxqWlZWellXZGxUMjVzZVNJNmRISjFaU3dpWm1seWMzUk1iMmRwYmlJNlptRnNY3dPRFUyTENKcFlYUWlPakUzTURJMU56QXlOVFlzSW5WelpYSnVZVzFsSWpvaVlYTmphRzVwZEhwbGNrQndZV3h2WVd4MGIyNWxkSGR2Y210ekxtTnZiU0lzSW5WelpYSlNiMnhsVG1GdFpTSTZJbE41YzNSbGJTQkJaRzFwYmlKOS42RFdTZGFzbmZ1RTliTXNGNHJFOFViZnAzOXh5Z2cxOVFaMUpUQ09Jc2tnIiwiaXNzIjoidHdpc3Rsb2NrIiwiZXhwIjoxNzAyNTczODYwfQ.PzDdAFmQqCWa6eT3ZA1_moqviO2cxsUMljrmNaWQkvg” https://us-west1.cloud.twistlock.com/us-4-161058134/api/v1/util/twistcli > twistcli;
      - run: ls -ltr
      - run: chmod a+x twistcli
      - run: ./twistcli images scan --token “$TW_TOKEN” bridgecrew/transporter
  build:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          directory: ‘.’
          soft-fail: true
          api-key-variable: BC_API_KEY
          prisma-api-url: PRISMA_API_URL
workflows:
  tryoutmultiple:
    jobs:
      - checkov_scan
